version: '3.2'

services:
  symfony:
    build:
      context: .
      dockerfile: build/symfony/Dockerfile
    container_name: site-template.symfony
    ports:
     - "83:80"
    volumes:
      - .:/var/www/html
    networks:
      - backend
  nginx:
    image: nginx:mainline-alpine
    container_name: site-template.nginx
    env_file:
      - .env
    volumes:
      - ./build/sites.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/api_dev.nginx.conf:/etc/nginx/api_dev.conf:ro
      - ./build/rules.vhost.nginx.conf:/etc/nginx/rules.vhost.conf:ro
      - ./public:/var/www/html/public
    extra_hosts:
      - "localbox:${MACHINE_IP}"
    ports:
      - 1337:80
#      - 3308:3308
#      - 3317:3317
    links:
      - symfony:phphost
    networks:
      - backend
  mysql:
      image: mysql:5.7
      container_name: site-template.mysql
      environment:
        MYSQL_DATABASE: ghost_drive
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ~/.docker-mysql-databases/ghost_drive:/var/lib/mysql
      ports:
        - "3307:3306"
      networks:
        backend:
          aliases:
            - mysql-host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: site-template.phpmyadmin
    environment:
      PMA_HOST: mysql-host
    ports:
      - "3309:80"
    networks:
      - backend

  redis:
    image: redis:3
    container_name: site-template.redis
    ports:
      - 6379:6379
    logging:
      driver: none
    networks:
      - backend

  redis-commander:
    image: tenstartups/redis-commander
    container_name: site-template.redis-commander
    command: --redis-host redis
    ports:
      - 6380:8081
    networks:
      - backend
    logging:
      driver: none

networks:
  backend: ~