#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app:
    resource: ../src/Controller/
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"